// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgdozanycjjnhzkkjurd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZG96YW55Y2pqbmh6a2tqdXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDAyMTEsImV4cCI6MjA2OTQxNjIxMX0.DdiNJF1PTEkmYQoMq6rtM2K0Xw1HRZL3zwX_blcGhE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});